"""Defining the AlgorithmNodeTreeManager class."""

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, cast

from valanga import BranchKey

from anemone import trees
from anemone.dynamics import SearchDynamics
from anemone.indices.index_manager import (
    NodeExplorationIndexManager,
)
from anemone.indices.index_manager.node_exploration_manager import (
    update_all_indices,
)
from anemone.node_evaluation.direct import (
    EvaluationQueries,
    NodeDirectEvaluator,
)
from anemone.node_factory.algorithm_node_factory import AlgorithmNodeFactory
from anemone.nodes.algorithm_node.algorithm_node import (
    AlgorithmNode,
)
from anemone.updates.depth_index_propagator import DepthIndexPropagator
from anemone.updates.value_propagator import ValuePropagator

from .tree_expander import TreeExpansion, TreeExpansions, record_tree_expansion
from .tree_manager import TreeManager

if TYPE_CHECKING:
    from anemone import node_selector as node_sel
    from anemone.node_evaluation.tree.adversarial.node_minmax_evaluation import (
        NodeMinmaxEvaluation,
    )


@dataclass
class AlgorithmNodeTreeManager[NodeT: AlgorithmNode[Any] = AlgorithmNode[Any]]:
    """Manage expansion, evaluation, upward propagation, and index refresh.

    This class wraps :class:`TreeManager` to add AlgorithmNode-specific behavior
    such as evaluation queries, value propagation, descendant-depth
    propagation, and exploration-index refresh.
    """

    tree_manager: TreeManager[NodeT]
    algorithm_tree_node_factory: AlgorithmNodeFactory

    evaluation_queries: EvaluationQueries
    node_evaluator: NodeDirectEvaluator | None
    index_manager: NodeExplorationIndexManager
    value_propagator: ValuePropagator = field(default_factory=ValuePropagator)
    depth_index_propagator: DepthIndexPropagator | None = None

    @property
    def dynamics(self) -> SearchDynamics[Any, Any]:
        """Return the search dynamics used by the wrapped tree manager."""
        return self.tree_manager.dynamics

    def open_tree_expansion_from_branch(
        self,
        tree: trees.Tree[NodeT],
        parent_node: NodeT,
        branch: BranchKey,
    ) -> TreeExpansion[NodeT]:
        """Open a child node for a specific branch and register it for evaluation.

        Args:
            tree: The tree to expand.
            parent_node: The node to expand.
            branch: The branch key to open from the parent node.

        Returns:
            The resulting tree expansion.

        """
        tree_expansion: TreeExpansion[NodeT]
        tree_expansion = self.tree_manager.open_tree_expansion_from_branch(
            tree=tree, parent_node=parent_node, branch=branch
        )

        cast(
            "NodeMinmaxEvaluation[Any, Any]", parent_node.tree_evaluation
        ).branches_to_explore.append(
            branch
        )  # default action checks for exactness are performed later

        return tree_expansion

    def open_instructions(
        self,
        tree: trees.Tree[NodeT],
        opening_instructions: "node_sel.OpeningInstructions[NodeT]",
    ) -> TreeExpansions[NodeT]:
        """Apply multiple opening instructions and evaluate any created child nodes.

        Args:
            tree: The tree to expand.
            opening_instructions: The opening instructions to apply.

        Returns:
            The expansions that were performed.

        """
        # place to store the tree expansion logs generated by the openings
        tree_expansions: TreeExpansions[NodeT] = TreeExpansions()

        opening_instruction: node_sel.OpeningInstruction[NodeT]
        tree_expansion: TreeExpansion[NodeT]
        for opening_instruction in opening_instructions.values():
            # open
            assert isinstance(opening_instruction.node_to_open, AlgorithmNode)
            tree_expansion = self.open_tree_expansion_from_branch(
                tree=tree,
                parent_node=opening_instruction.node_to_open,
                branch=opening_instruction.branch,
            )

            record_tree_expansion(
                tree=tree,
                tree_expansions=tree_expansions,
                tree_expansion=tree_expansion,
            )

        assert self.node_evaluator is not None
        for tree_expansion in tree_expansions.expansions_with_node_creation:
            # TODO: give the tree expansion to the function directly
            assert isinstance(tree_expansion.child_node, AlgorithmNode)
            self.node_evaluator.add_evaluation_query(
                node=tree_expansion.child_node,
                evaluation_queries=self.evaluation_queries,
            )

        self.node_evaluator.evaluate_all_queried_nodes(
            evaluation_queries=self.evaluation_queries
        )

        return tree_expansions

    def refresh_exploration_indices(self, tree: trees.Tree[NodeT]) -> None:
        """Refresh exploration indices as a phase distinct from value propagation.

        Value propagation, descendant-depth propagation, and index refresh are
        intentionally separate phases. The upward propagation steps are
        incremental, while index refresh remains delegated to the repository's
        dedicated index logic because index dependencies here are heterogeneous
        and not uniformly backward.
        """
        update_all_indices(index_manager=self.index_manager, tree=tree)

    def update_indices(self, tree: trees.Tree[NodeT]) -> None:
        """Backward-compatible alias for ``refresh_exploration_indices``."""
        self.refresh_exploration_indices(tree=tree)

    def update_backward(self, tree_expansions: TreeExpansions[NodeT]) -> None:
        """Propagate value changes upward from the latest structural expansions.

        Args:
            tree_expansions: The expansions that triggered the updates.

        Returns:
            None

        """
        changed_nodes = self._collect_changed_nodes_from_expansions(
            tree_expansions=tree_expansions
        )
        if not changed_nodes:
            return

        # Value propagation is intentionally separate from exploration-index
        # refresh. The caller performs the explicit index refresh step after this
        # value-only propagation pass.
        self.value_propagator.propagate_from_changed_nodes(changed_nodes)

    def propagate_depth_index(self, tree_expansions: TreeExpansions[NodeT]) -> None:
        """Propagate descendant-depth metadata separately from value updates.

        ``MaxDepthDescendants`` is an upward structural summary, not part of
        value propagation and not part of the top-down exploration-index refresh
        phase. This hook keeps that metadata alive without restoring the removed
        mixed updater pipeline.
        """
        if self.depth_index_propagator is None:
            return

        changed_nodes = self._collect_changed_nodes_from_expansions(
            tree_expansions=tree_expansions
        )
        if not changed_nodes:
            return

        self.depth_index_propagator.propagate_from_changed_nodes(changed_nodes)

    def _collect_changed_nodes_from_expansions(
        self,
        *,
        tree_expansions: TreeExpansions[NodeT],
    ) -> list[NodeT]:
        """Return the nodes that seed the next upward propagation wave.

        Newly created children have just received direct evaluation in
        ``open_instructions``. Existing children can also appear here when a new
        structural link is added to an already-known node. In both cases, the
        expanded child node is the smallest accurate seed for marking parents
        dirty without preemptively seeding arbitrary ancestors.

        This mirrors the old ``generate_update_instructions(...)`` seeding
        behavior: each ``tree_expansion.child_node`` was treated as an initial
        "new value" source without additional semantic filtering. The same seed
        rule is also correct for descendant-depth propagation because a newly
        linked or newly created child is the structural fact its parents must
        observe.
        """
        return [tree_expansion.child_node for tree_expansion in tree_expansions]

    def print_some_stats(self, tree: trees.Tree[NodeT]) -> None:
        """Print statistics about the given tree.

        Args:
            tree: The tree to print statistics for.

        Returns:
            None

        """
        self.tree_manager.print_some_stats(tree=tree)

    def print_best_line(self, tree: trees.Tree[NodeT]) -> None:
        """Print the best branch line based on the current tree evaluation.

        Args:
            tree: The tree containing branches and their evaluations.

        """
        cast(
            "NodeMinmaxEvaluation[Any, Any]", tree.root_node.tree_evaluation
        ).print_best_line()
